[build]
  base = "Frontend"  # This points to the root folder where your frontend project is
  command = "CI= npm run build"  # Build command
  publish = "build"  # The correct build directory path


# Redirects for React Router or similar client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
