[build]
  base = "Frontend"  # Ensure this points to the root of your frontend folder
  command = "CI= npm run build"
  publish = "Frontend/build"  # Correct the publish path to point to the build folder

# Redirects for React Router or similar client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
