[build]
  # The base directory where your frontend code is located
  base = "Frontend"
  
  # The command that Netlify will run to build the project
  command = "CI= npm run build"
  
  # The directory where Netlify should look for the build output
  publish = "Frontend/build"

# Optional: Redirects for client-side routing (useful for React Router or other frontend routing libraries)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

